#!/bin/sh

uci -q batch << 'EOF'
	# 时区改成中国
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	set system.@system[0].clock_timestyle='1'
	set system.@system[0].clock_hourcycle='h23'
	
	delete system.ntp.server
	add_list system.ntp.server='cn.pool.ntp.org'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='time1.cloud.tencent.com'
	add_list system.ntp.server='ntp.aliyun.com'
	commit system
	
	
	# 去掉加速
	set firewall.@defaults[0].flow_offloading='0'
	set firewall.@defaults[0].flow_offloading_hw='0'
	commit firewall

	# lan默认ip 
	set network.lan.ipaddr='192.168.2.1'
	commit network
	
	# 网络诊断的3个默认ip
	set luci.diag.dns='www.baidu.com'
	set luci.diag.ping='www.baidu.com'
	set luci.diag.route='www.baidu.com'
	commit luci
	

EOF

# coremark
chmod +x /etc/coremark.sh
echo '0 4 * * * /etc/coremark.sh firstbenchmark' >> /etc/crontabs/root

# 禁用dnsmasq log
if [ -f /etc/dnsmasq.conf ];then
	sed -i -E '/^log-facility=/d' /etc/dnsmasq.conf
	echo 'log-facility=/dev/null' >> /etc/dnsmasq.conf
fi

# root shell默认改bash
if [ -x /bin/bash ];then
	sed -E -i '/^root/{s#:/bin/.*#:/bin/bash#}' /etc/passwd
fi

# r81驱动加载顺序
for m in r8125 r8125-rss r8126 r8126-rss r8127 r8127-rss r8168 r8168-rss r8169;do
	if [ -L "/etc/modules-boot.d/$m" ];then
		mv "/etc/modules-boot.d/$m" "/etc/modules-boot.d/36-$m"
	fi
done

# 默认禁用r81驱动
if [ -f /etc/modules.d/r8169 ];then
	cat >> /etc/modules.conf <<'EOF'
blacklist r8168
blacklist r8125
blacklist r8125-rss
blacklist r8126
blacklist r8126-rss
blacklist r8127
blacklist r8127-rss
EOF

fi

# 北大源
sed -i.ori 's,://downloads.openwrt.org/,://mirrors.pku.edu.cn/openwrt/,' /etc/apk/repositories.d/distfeeds.list

# 默认密码改成password
echo -e 'password\npassword' | passwd root 

# openssh开启root登录
if [ -f /etc/ssh/sshd_config ];then
	sed -i '/^#PermitRootLogin /c\PermitRootLogin yes' /etc/ssh/sshd_config
fi

添加自动还原配置脚本
chmod +x /etc/autorestoreop.sh
sed -E -i '/^exit /i\
/etc/autorestoreop.sh & 
' /etc/rc.local 

exit 0


