#!/bin/sh

uci -q batch << 'EOF'
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	
	delete system.ntp.server
	add_list system.ntp.server='cn.pool.ntp.org'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='time1.cloud.tencent.com'
	add_list system.ntp.server='ntp.aliyun.com'
	
	commit system
	
	delete firewall.@zone[1].fullcone6
	
	commit firewall

	set network.lan.ipaddr='192.168.2.1'
	
	commit network
EOF

chmod +x /etc/coremark.sh
echo '0 4 * * * /etc/coremark.sh firstbenchmark' >> /etc/crontabs/root

if [ -f /etc/dnsmasq.conf ];then
	sed -i -E '/^log-facility=/d' /etc/dnsmasq.conf
	echo 'log-facility=/dev/null' >> /etc/dnsmasq.conf
fi


if [ -x /bin/bash ];then
	sed -E -i '/^root/{s#:/bin/.*#:/bin/bash#}' /etc/passwd
fi

chmod +x /etc/disservices.sh

# 腾讯源

sed -i.ori 's,://downloads.openwrt.org/,://mirrors.cloud.tencent.com/openwrt/,' /etc/opkg/distfeeds.conf

# 默认密码改成password
echo -e 'password\npassword' | passwd root 

exit 0
