#!/bin/sh

uci -q batch << EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	
	delete system.ntp.server
	add_list system.ntp.server='cn.pool.ntp.org'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='time1.cloud.tencent.com'
	add_list system.ntp.server='ntp.aliyun.com'
	
	commit system
	
	delete firewall.@zone[1].fullcone6
	
	commit firewall

	
EOF

chmod +x /etc/coremark.sh
echo '0 4 * * * /etc/coremark.sh firstbenchmark' >> /etc/crontabs/root

if [ -f /etc/dnsmasq.conf ];then
	sed -i -E '/^log-facility=/d' /etc/dnsmasq.conf
	echo 'log-facility=/dev/null' >> /etc/dnsmasq.conf
fi

if [ -f /etc/config/upnpd ];then
	uci set upnpd.config.external_ip='223.5.5.5'
	uci commit upnpd
fi

if [ -x /bin/bash ];then
	sed -E -i '/^root/{s#:/bin/.*#:/bin/bash#}' /etc/passwd
fi

services="aria2
banip
cpulimit
ddns
frpc
frps
msd_lite
mwan3
natmap
netdata
omcproxy
p910nd
samba4
socat
timewol
udpxy
usb_printer
uugamebooster"

for s in $services; do 
	echo "$s"
	service "$s" disable
	service "$s" stop
done


exit 0
