#!/bin/sh

#eth0 
echo 2 > /proc/irq/$(cat /proc/interrupts | grep -E '\s+eth0' | grep -Eo  '[0-9]+' | head -n1)/smp_affinity

#eth1 usb网卡
echo 8 > /proc/irq/$(cat /proc/interrupts | grep -E '\s+xhci-hcd:usb2' | grep -Eo  '[0-9]+' | head -n1)/smp_affinity

#queues on all cores
echo 5 > /sys/class/net/eth0/queues/rx-0/rps_cpus
echo 5 > /sys/class/net/eth1/queues/rx-0/rps_cpus
echo 5 > /sys/class/net/eth0/queues/tx-0/xps_cpus
echo 5 > /sys/class/net/eth1/queues/tx-0/xps_cpus

